-- ============================================================
-- V005: 每日提醒表
-- Schema : CUSTGROUP
-- 保留策略：应用层写入时清理 alert_date < SYSDATE - 30 的记录
-- ============================================================

CREATE TABLE CUSTGROUP.AIPC_MAN_ALERT (
    ALERT_ID       NUMBER         GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMPLOYEE_ID    VARCHAR2(32)   NOT NULL,           -- 营销人员 OA 工号
    ALERT_CONTENT  VARCHAR2(500)  NOT NULL,           -- 提醒内容
    ALERT_DATE     DATE           DEFAULT TRUNC(SYSDATE) NOT NULL,  -- 提醒日期（精确到天）
    IS_DONE        NUMBER(1)      DEFAULT 0 NOT NULL, -- 0=未完成 1=已完成
    CREATE_TIME    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATE_TIME    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON TABLE  CUSTGROUP.AIPC_MAN_ALERT                IS '客户分配系统-营销人员每日提醒表';
COMMENT ON COLUMN CUSTGROUP.AIPC_MAN_ALERT.ALERT_ID       IS '主键，自增';
COMMENT ON COLUMN CUSTGROUP.AIPC_MAN_ALERT.EMPLOYEE_ID    IS '营销人员 OA 工号';
COMMENT ON COLUMN CUSTGROUP.AIPC_MAN_ALERT.ALERT_CONTENT  IS '提醒内容，最长500字';
COMMENT ON COLUMN CUSTGROUP.AIPC_MAN_ALERT.ALERT_DATE     IS '提醒日期（按天），用于展示分组';
COMMENT ON COLUMN CUSTGROUP.AIPC_MAN_ALERT.IS_DONE        IS '完成标识：0=未完成，1=已完成';
COMMENT ON COLUMN CUSTGROUP.AIPC_MAN_ALERT.CREATE_TIME    IS '创建时间';
COMMENT ON COLUMN CUSTGROUP.AIPC_MAN_ALERT.UPDATE_TIME    IS '最后更新时间（标记完成时更新）';

-- 常用查询索引
CREATE INDEX IDX_ALERT_EMP_DATE ON CUSTGROUP.AIPC_MAN_ALERT (EMPLOYEE_ID, ALERT_DATE);
